# Generated by Django 5.1.3 on 2024-11-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThaiConsonant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('thai_word', models.CharField(max_length=255)),
                ('rtgs', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('emoji', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'ordering': ['ranking'],
            },
        ),
    ]
