# Generated by Django 5.1.3 on 2024-11-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thai_words', '0002_thaivowel'),
    ]

    operations = [
        migrations.AddField(
            model_name='thaiconsonant',
            name='audio_pronunciation',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
