# Generated by Django 5.1.3 on 2024-11-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thai_words', '0003_thaiconsonant_audio_pronunciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('word', models.CharField(max_length=255)),
                ('rtgs', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('mp3', models.FileField(blank=True, null=True, upload_to='ten_words_mp3/')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
